version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: spring_batch_postgres
    environment:
      POSTGRES_USER: batch_user
      POSTGRES_PASSWORD: batch_password
      POSTGRES_DB: batch_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
