-- Clean up Spring Batch metadata tables

DELETE FROM BATCH_STEP_EXECUTION_CONTEXT;
DELETE FROM BATCH_STEP_EXECUTION;
DELETE FROM BATCH_JOB_EXECUTION_CONTEXT;
DELETE FROM BATCH_JOB_EXECUTION_PARAMS;
DELETE FROM BATCH_JOB_EXECUTION;
DELETE FROM BATCH_JOB_INSTANCE;

-- Optionally reset sequences (if using PostgreSQL sequences):

ALTER SEQUENCE batch_step_execution_seq RESTART WITH 1;
ALTER SEQUENCE batch_job_execution_seq RESTART WITH 1;
ALTER SEQUENCE batch_job_seq RESTART WITH 1;